#!/usr/bin/env python3
"""
HTML generator module for the weekly report system.
Handles generating HTML content from Excel data.
"""

import logging
from src.constants import HTML_TABLE_CLASS

logger = logging.getLogger(__name__)

class HtmlGenerator:
    """Handles generating HTML content from Excel data."""
    
    def __init__(self):
        pass
    
    def generate_html(self, excel_data) -> str:
        """
        Generate HTML table from Excel data model.
        
        Args:
            excel_data: ExcelData object containing title, headers, and rows
            
        Returns:
            str: HTML table content
        """
        try:
            # Build HTML table
            html = [f'<table class="{HTML_TABLE_CLASS}" border="1" cellspacing="0" cellpadding="4">']
            
            # Add title row
            html.append('  <thead>')
            html.append('    <tr>')
            html.append(f'      <th colspan="{len(excel_data.headers)}" style="text-align: center; font-weight: bold; font-size: 14pt;">{excel_data.title}</th>')
            html.append('    </tr>')
            
            # Add header row
            html.append('    <tr>')
            for header in excel_data.headers:
                html.append(f'      <th>{header}</th>')
            html.append('    </tr>')
            html.append('  </thead>')
            
            # Add data rows
            html.append('  <tbody>')
            
            for row in excel_data.rows:
                html.append('    <tr>')
                for cell in row.cells:
                    # Build style attribute
                    style_attrs = []
                    if cell.style:
                        for key, value in cell.style.items():
                            style_attrs.append(f'{key}: {value}')
                    style_str = '; '.join(style_attrs)
                    style_html = f' style="{style_str}"' if style_str else ''
                    
                    # Build cell HTML
                    if cell.rowspan > 1 or cell.colspan > 1:
                        html.append(f'      <td{style_html} rowspan="{cell.rowspan}" colspan="{cell.colspan}">{cell.value}</td>')
                    else:
                        html.append(f'      <td{style_html}>{cell.value}</td>')
                html.append('    </tr>')
            html.append('  </tbody>')
            html.append('</table>')
            
            # Add CSS styling
            style = self.generate_styles()
            html_content = style + '\n'.join(html)
            
            return html_content
            
        except Exception as e:
            logger.error(f"Error generating HTML: {str(e)}")
            raise
    
    def generate_html_from_excel(self, excel_content):
        """
        Generate complete HTML email from Excel content.
        
        Args:
            excel_content: HTML table content generated by generate_html
            
        Returns:
            str: Complete HTML content for email
        """
        try:
            # Add email template around the Excel content
            html_body = f"""
            <html>
              <head></head>
              <body>
                <p>Dear Team,</p>
                <p>Please find attached the weekly report.</p>
                <p>Best regards,</p>
                <p>Automated Report System</p>
                <hr>
                <h2>Weekly Report Content:</h2>
                {excel_content}
              </body>
            </html>
            """
            
            return html_body
            
        except Exception as e:
            logger.error(f"Error generating HTML: {str(e)}")
            raise
    
    def generate_styles(self):
        """
        Generate CSS styles for the HTML content.
        
        Returns:
            str: CSS styles
        """
        return """
        <style>
            .excel-table {
                border-collapse: collapse;
                width: 100%;
                font-family: Arial, sans-serif;
                font-size: 12px;
                margin: 0 auto;
            }
            .excel-table th, .excel-table td {
                border: 1px solid #ddd;
                padding: 8px;
                text-align: left;
            }
            .excel-table th {
                background-color: #f2f2f2;
                font-weight: bold;
                text-align: center;
            }
            .excel-table tr:nth-child(even) {
                background-color: #f9f9f9;
            }
            .excel-table tr:hover {
                background-color: #f5f5f5;
            }
        </style>
        """