#!/usr/bin/env python3
"""
HTML generator module for the weekly report system.
Handles generating HTML content from Excel data.
"""

import logging

logger = logging.getLogger(__name__)

class HtmlGenerator:
    """Handles generating HTML content from Excel data."""
    
    def __init__(self):
        pass
    
    def generate_html_from_excel(self, excel_content):
        """
        Generate HTML content from Excel data.
        
        Args:
            excel_content: HTML content generated by ExcelReader
            
        Returns:
            str: Complete HTML content for email
        """
        try:
            # Add email template around the Excel content
            html_body = f"""
            <html>
              <head></head>
              <body>
                <p>Dear Team,</p>
                <p>Please find attached the weekly report.</p>
                <p>Best regards,</p>
                <p>Automated Report System</p>
                <hr>
                <h2>Weekly Report Content:</h2>
                {excel_content}
              </body>
            </html>
            """
            
            return html_body
            
        except Exception as e:
            logger.error(f"Error generating HTML: {str(e)}")
            raise
    
    def generate_styles(self):
        """
        Generate CSS styles for the HTML content.
        
        Returns:
            str: CSS styles
        """
        return """
        <style>
            .excel-table {
                border-collapse: collapse;
                width: 100%;
                font-family: Arial, sans-serif;
                font-size: 12px;
                margin: 0 auto;
            }
            .excel-table th, .excel-table td {
                border: 1px solid #ddd;
                padding: 8px;
                text-align: left;
            }
            .excel-table th {
                background-color: #f2f2f2;
                font-weight: bold;
                text-align: center;
            }
            .excel-table tr:nth-child(even) {
                background-color: #f9f9f9;
            }
            .excel-table tr:hover {
                background-color: #f5f5f5;
            }
        </style>
        """